# Generated by Django 3.0.7 on 2020-06-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchw', '0002_auto_20200622_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=12),
        ),
    ]
