# Generated by Django 3.0.7 on 2020-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchw', '0004_auto_20200623_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default='none', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Dress', 'Dress'), ('Sports', 'Sports'), ('Smart', 'Smart')], max_length=25),
        ),
    ]
