# Generated by Django 3.0.7 on 2020-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchw', '0008_auto_20200624_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('order_confirmed', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, related_name='past_orders', to='watchw.Item')),
            ],
        ),
    ]
