# Generated by Django 3.0.7 on 2020-06-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchw', '0011_couponcode_discount_pecentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='discount_pecentage',
            new_name='discount_percentage',
        ),
    ]
