# Generated by Django 3.0.7 on 2020-06-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchw', '0012_auto_20200626_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
